Jjdzr13 fi 45
infoshareacademy/JJDZR13-FreshmenIndustries pull request #10
Opened 2024-03-12 10:10 UTC by michalwabnik

2024-03-12 19:42 UTC, TomaszOdwald requested changes
Jeszcze taka ogólna uwaga, między niektórymi funkcjami nie masz linii przerwy. W IntelliJu tego tak nie widać, ale w interfejsie GitHuba widać

2024-03-12 19:42 UTC, TomaszOdwald commented on web/src/main/java/pl/isa/freshmenindustries/controller/GameController.java
> +            gameService.createGame(game);
Mając w kontrolerze blok try/catch oznacza, że masz powiązanie z tym jak jest zaimplementowany service i każda inna implementacja service'u powinna też rzucać jakiś wyjątek. Lepiej zrobić to na zasadzie zwracania wyniku, tj. czy udało się dodać czy nie, i na podstawie wyniku definiujesz co pokazać użytkownikowi.

2024-03-12 19:42 UTC, TomaszOdwald commented on web/src/main/java/pl/isa/freshmenindustries/game/GameRepositoryImplementation.java
> +    File gamesFilePath = new File("C:\\Users\\mwabnik\\JJDZR13-FreshmenIndustries\\web\\src\\main\\resources\\source\\games.json");
Ta ścieżka będzie działać tylko u Ciebie ;)

2024-03-12 19:42 UTC, TomaszOdwald commented on web/src/main/java/pl/isa/freshmenindustries/game/GameRepositoryImplementation.java
> +            log.info(e.getMessage());
Przy błędach odczytu/zapisu można też się zastanowić, czy nie warto przekazywać tą informację gdzieś wyżej, żeby móc poinformować użytkownika, że czegoś nie udało się zrobić. Oczywiście lepiej wartością zwracaną niż wyjątkami ;)

2024-03-12 19:42 UTC, TomaszOdwald commented on web/src/main/java/pl/isa/freshmenindustries/game/GameService.java
> +            throw new IllegalArgumentException("Missing name or description");
Wyjątek nie jest tu raczej potrzebny, dopiero kontroler może sprawdzić zawartość i wyświetlić użytkownikowi odpowiedni komunikat. Wyjątki powinny występować tylko tam, gdzie nie jesteśmy w stanie czegoś przewidzieć. Natomiast to, że ktoś podał nazwę, której może nie być, jest raczej standardowym zachowaniem, na które jesteśmy w stanie zaprojektować logikę w przewidywalny sposób.

2024-03-13 10:02 UTC, michalwabnik commented on web/src/main/java/pl/isa/freshmenindustries/game/GameRepositoryImplementation.java
> +    File gamesFilePath = new File("C:\\Users\\mwabnik\\JJDZR13-FreshmenIndustries\\web\\src\\main\\resources\\source\\games.json");
Próbowałem na wszelkie mi znane sposoby podmienić ten path, ale nic nie działa. Pomożesz?

2024-03-14 20:17 UTC, merged