Add user roles
infoshareacademy/JJDZR13-FreshmenIndustries pull request #17
Opened 2024-06-04 08:24 UTC by michalwabnik

2024-06-06 19:12 UTC, TomaszOdwald requested changes

2024-06-06 19:12 UTC, TomaszOdwald commented on web/src/main/java/pl/isa/freshmenindustries/user/RolesEnum.java
Ten enum mógłby się jak dla mnie znaleźć w klasie Role, byłoby w jednym miejscu i od razu wiadomo gdzie szukać

2024-06-06 19:12 UTC, TomaszOdwald commented on web/src/main/java/pl/isa/freshmenindustries/config/SecurityConfig.java
> +//              .userDetailsService(userDetailsService)
Czemu to jest zakomentowane?

2024-06-06 19:12 UTC, TomaszOdwald commented on web/src/main/java/pl/isa/freshmenindustries/user/UserRepository.java
> +import java.util.Optional;
Zaimportowany Optional, ale nigdzie nie użyty?

2024-06-07 06:31 UTC, michalwabnik commented on web/src/main/java/pl/isa/freshmenindustries/user/RolesEnum.java
Poprawiłem

2024-06-07 06:31 UTC, michalwabnik commented on web/src/main/java/pl/isa/freshmenindustries/config/SecurityConfig.java
> +//              .userDetailsService(userDetailsService)
Poprawiłem

2024-06-07 06:32 UTC, michalwabnik commented on web/src/main/java/pl/isa/freshmenindustries/user/UserRepository.java
> +import java.util.Optional;
Usunąłem

2024-06-07 06:35 UTC, merged