Add Manage Game Option functionality
infoshareacademy/JJDZR13-FreshmenIndustries pull request #2
Opened 2024-01-22 08:58 UTC by michalwabnik

Czekam jeszcze na pozostałe funkcjonalności

2024-01-22 09:04 UTC, michalwabnik commented on src/main/java/pl/isa/freshmenindustries/manage_game/ManageGameUtilise.java
> +            case 3: System.out.println("Odpalamy opcje 3");
Tu będą opcje do uruchomienia jakieś klasy

2024-01-22 09:05 UTC, michalwabnik commented on src/main/java/pl/isa/freshmenindustries/manage_game/ManageGameUtilise.java
> +    }
Może zrobić z tego osobną klasę, która będzie wykorzystywana w pozostałych miejscach

2024-01-26 19:58 UTC, TomaszOdwald requested changes

2024-01-26 19:58 UTC, TomaszOdwald commented on src/main/java/pl/isa/freshmenindustries/Main.java
> +
Po co 2 nowe linie?

2024-01-26 19:58 UTC, TomaszOdwald commented on src/main/java/pl/isa/freshmenindustries/manage_game/GameUtils.java
> +>>>>>>> 4a3bc2f (Refactor)
Tu wygląda jakby coś było przesuwane między branchami i nie powinno być żadnych <<< === >>> w kodzie.

2024-01-26 19:58 UTC, TomaszOdwald commented on src/main/java/pl/isa/freshmenindustries/manage_game/ManageGameSimulation.java
> +    private String errorMessage = "Incorrect value. Please try again: ";
Można wszędzie dodać final, a do nich też często stosujemy notację ERROR_MESSAGE, żeby wyróżnić stałe wartości.

2024-01-26 19:58 UTC, TomaszOdwald commented on src/main/java/pl/isa/freshmenindustries/manage_game/ManageGameUtils.java
> +public class ManageGameUtils {
Klasa, która coś przechowuje, nie powinna się nazywać Utils, takie klasy posiadają jedynie jakieś zmienne i funkcje pomocnicze. ManageGameMenu byłoby już lepszą nazwą ;)

2024-01-26 19:58 UTC, TomaszOdwald commented on src/main/java/pl/isa/freshmenindustries/manage_game/Game.java
> +package pl.isa.freshmenindustries.manage_game;
Nazwa pakietu nie powinna mieć żadnych znaków poza małymi literami, czyli `pl.isa.freshmenindustries.managegame`

2024-01-27 14:34 UTC, TomaszOdwald approved these changes

2024-01-27 14:34 UTC, merged