update
infoshareacademy/JJDZR13-FreshmenIndustries pull request #9
Opened 2024-02-15 18:09 UTC by AdrianLipinski90

New class AddNewGame added, and Main updated

2024-02-16 18:45 UTC, TomaszOdwald requested changes

2024-02-16 18:45 UTC, TomaszOdwald commented on src/main/java/pl/isa/freshmenindustries/game/GameStarter.java
> +//    static private Scanner scanner;
Usuń zakomentowany kod

2024-02-16 18:45 UTC, TomaszOdwald commented on src/main/java/pl/isa/freshmenindustries/game/GameList.java
> +    }
Co z tymi dwoma funkcjami, czemu są dodane, a nie zaimplementowane?

2024-02-18 17:41 UTC, AdrianLipinski90 commented on src/main/java/pl/isa/freshmenindustries/game/GameList.java
> +    }
są już nie potrzebne :)

2024-02-18 17:41 UTC, AdrianLipinski90 commented on src/main/java/pl/isa/freshmenindustries/game/GameStarter.java
> +//    static private Scanner scanner;
Usunięty

2024-02-18 17:42 UTC, merged